apiVersion: v1
kind: Service
metadata:
  name: libsclaw-service-nodeport
  namespace: libsclaw-ns
  labels:
    app: libsclaw-stack
spec:
  type: NodePort
  selector:
    app: libsclaw-stack
  ports:
    - name: napcat-web
      port: 6099
      targetPort: 6099
      # nodePort: 30099 # Optional: Specify a fixed NodePort if needed, otherwise remove this line
    - name: libsclaw-web
      port: 6185
      targetPort: 6185
      # nodePort: 30185 # Optional: Specify a fixed NodePort if needed, otherwise remove this line